#!/usr/bin/env bash
# updating the SSH config so a password is unneeded

Host 5583-web-01
    Hostname #!/usr/bin/env bash
# updating the SSH config so a password is unneeded

Host 5583-web-01
    Hostname 35.180.130.213
    User ubuntu
    IdentityFile ~/.ssh/school
    PassworkAuthentification no

Host 5583-web-02
    HostName 15.188.87.7
    User ubuntu
    IdentityFile ~/.ssh/school
    IdentitiesOnly yes

Host 5583-lb-01
    HostName 13.38.98.207
    User ubuntu
    IdentityFile ~/.ssh/school
    IdentitiesOnly yes
